# Discussion Packages in Bioconductor

## RESOLVE: An R package for the efficient analysis of mutational signatures from cancer genomes
### Author: Daniele Ramazzotti [aut] , Luca De Sano [cre, aut] 
### Ramazzotti D, De Sano L (2022). RESOLVE: RESOLVE: An R package for the efficient analysis of mutational signatures from cancer genomes. R package version 1.0.0, https://github.com/danro9685/RESOLVE.
Permite la extracción eficiente y la asignacion de firmas mutacionales comúnes en cáncer. Ayuda a la extracción, estimacion de exposicion y la revision de confianza.
Tiene buen ranking pero tiene menos de 50 descargas

## RgnTX
### Author: Yue Wang [aut, cre], Jia Meng [aut]
### Wang Y, Meng J (2022). RgnTX: Colocalization analysis of transcriptome elements in the presence of isoform heterogeneity and ambiguity. R package version 1.0.0.
Permite hacer anotaciones de transcriptomica para obtener un modelo de de patrpnes de splicing alternativo. También checa permutaciones para evaluar correlación entre las fucnines y las regiones del transcrito.
No tuvo muchas descargas pero tienen un buen ranking. No tiene liga para los debugging y funciona en todas las plataformas.

## crisprDesign
## Comprehensive design of CRISPR gRNAs for nucleases and base editors
### Author: Jean-Philippe Fortin [aut, cre], Luke Hoberecht [aut]
### Hoberecht L, Perampalam P, Lun A, Fortin J (2022). “A comprehensive Bioconductor ecosystem for the design of CRISPR guide RNAs across nucleases and technologies.” bioRxiv.
Contiene funciones que permiten diseñar y anotar la guia de RNA de CRISPR. Incluye cinco modalidades de CRIPR y soporta todos los tipos de nucleasas.
Tiene buenas descargas, casi ciento cincuenta en lo que va de enero. Tiene muchas dependencias y parece que es un paquete muy util.
